### PR TITLE
Fix a bug introduced in b0739a5

### LINKED ISSUE #93: html --output-table reports broke from #91 skipped diff changes
When trying to use the --output-table --html mode get this error.
```
 /bin/warmup_stats --output-table normal_results.html --html before_normal.json.bz2
Traceback (most recent call last):
  File "/bin/warmup_stats", line 504, in <module>
    main(options)
  File "/bin/warmup_stats", line 495, in main
    write_html_table(summary, options.output_table)
  File "/warmup/summary_statistics.py", line 499, in write_html_table
    skipped_before = [b for (b, v) in skipped[SKIPPED_BEFORE] if v == vm]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

I guess i didn't try using this mode in the earlier PR where it broke.

### PR DESCRIPTION
**Pull request by ltratt**
Sometimes "skipped" can be None, so check for that accordingly. Should fix #93.

@fsfod can you check that a) this fixes your immediate bug b) doesn't make your other major use cases break? This isn't part of the code I'm very familiar with, so it's a bit difficult to know if I've broken something that isn't the use case I'm trying.

### CODE REVIEW

**Comment by fsfod** [comment]
Yes it fixed the issue and i don't notice anything broken using the other modes

**Comment by ltratt** [comment]
OK, then you can merge I guess?
