### ISSUE TITLE
html --output-table reports broke from #91 skipped diff changes

### ISSUE THREAD

**Issue by fsfod** [softdevteam/warmup_stats#93]
When trying to use the --output-table --html mode get this error.
```
 /bin/warmup_stats --output-table normal_results.html --html before_normal.json.bz2
Traceback (most recent call last):
  File "/bin/warmup_stats", line 504, in <module>
    main(options)
  File "/bin/warmup_stats", line 495, in main
    write_html_table(summary, options.output_table)
  File "/warmup/summary_statistics.py", line 499, in write_html_table
    skipped_before = [b for (b, v) in skipped[SKIPPED_BEFORE] if v == vm]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

I guess i didn't try using this mode in the earlier PR where it broke.

**Comment by fsfod** [comment]
It only started happening after PR #91 , i put it in the title but i guess github doesn't want to make it a link in there.

**Comment by ltratt** [comment]
It looks like the bad commit is b0739a5a848e99224525d980eeaf34fdd5a0ac1c.
